'use strict'

const scale = {
    c: 0+(5*12),
    cis: 1+(5*12),
    d: 2+(5*12),
    dis: 3+(5*12),
    e: 4+(5*12),
    f: 5+(5*12),
    fis: 6+(5*12),
    g: 7+(5*12),
    gis: 8+(5*12),
    a: 9+(5*12),
    ais: 10+(5*12),
    h: 11+(5*12)
}

const voices = [
    {
        name: 'treble',
        startAt: 0, // start at the first loop
        notes: [
            scale.e,
            scale.e,
            scale.f,
            scale.g,
            scale.g,
            scale.f,
            scale.e,
            scale.d,
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.e,
            scale.d,
            scale.d,
            scale.e,
            scale.e,
            scale.f,
            scale.g,
            scale.g,
            scale.f,
            scale.e,
            scale.d,
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.d,
            scale.c,
            scale.c,
            scale.d,
            scale.d,
            scale.e,
            scale.c,
            scale.d,
            scale.e,
            scale.f,
            scale.e,
            scale.c,
            scale.d,
            scale.e,
            scale.f,
            scale.e,
            scale.d,
            scale.c,
            scale.d,
            scale.g-12,
            scale.e,
            scale.e,
            scale.f,
            scale.g,
            scale.g,
            scale.f,
            scale.e,
            scale.d,
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.d,
            scale.c,
            scale.c
        ]
    }, {
        name: 'bass',
        startAt: 1, // start at second loop
        notes: [
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.e,
            scale.d,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.e-12,
            scale.g-12,
            scale.c,
            scale.c,
            scale.g-12,
            scale.g-12,
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.e,
            scale.d,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.e-12,
            scale.g-12,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.e-12,
            scale.g-12,
            scale.g-12,
            scale.c,
            scale.e-12,
            scale.g-12,
            scale.c,
            scale.d,
            scale.c,
            scale.e-12,
            scale.g-12,
            scale.c,
            scale.d,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.g-12,
            scale.g-24,
            scale.c,
            scale.c,
            scale.d,
            scale.e,
            scale.e,
            scale.d,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.e-12,
            scale.g-12,
            scale.c,
            scale.g-12,
            scale.e-12,
            scale.e-12
        ]
    }
]

module.exports = voices
