'use strict'

const scale = {
    c: 0+(5*12)+2,
    cis: 1+(5*12)+2,
    d: 2+(5*12)+2,
    dis: 3+(5*12)+2,
    e: 4+(5*12)+2,
    f: 5+(5*12)+2,
    fis: 6+(5*12)+2,
    g: 7+(5*12)+2,
    gis: 8+(5*12)+2,
    a: 9+(5*12)+2,
    ais: 10+(5*12)+2,
    h: 11+(5*12)+2
}

const voices = [
    {
        name: 'intro',
        startAt: 0, // start at the first note
        endAt: 55, // end at the 55th note
        notes: [
            // part 1
            scale.e,
            scale.h-12,
            scale.c,
            scale.d,
            scale.c,
            scale.h-12,
            scale.a-12,
            scale.a-12,
            scale.c,
            scale.e,
            scale.d,
            scale.c,
            scale.h-12,
            scale.h-12,
            scale.c,
            scale.d,
            scale.e,
            scale.c,
            scale.a-12,
            scale.a-12,
            scale.d,
            scale.f,
            scale.a,
            scale.g,
            scale.f,
            scale.e,
            scale.e,
            scale.c,
            scale.e,
            scale.d,
            scale.c,
            scale.h-12,
            scale.h-12,
            scale.c,
            scale.d,
            scale.e,
            scale.c,
            scale.a-12,
            scale.a-12,
            // part 2
            scale.e,
            scale.c,
            scale.d,
            scale.h-12,
            scale.c,
            scale.a-12,
            scale.gis-12,
            scale.h-12,
            scale.e,
            scale.c,
            scale.d,
            scale.h-12,
            scale.c,
            scale.e,
            scale.a,
            scale.gis
        ]
    }, {
        name: 'soprano',
        startAt: 55, // start at the 56th note
        endAt: Infinity,
        notes: [
            // part 1
            scale.e,
            null,
            scale.h-12,
            scale.c,
            scale.d,
            null,
            scale.c,
            scale.h-12,
            scale.a-12,
            null,
            scale.a-12,
            scale.c,
            scale.e,
            null,
            scale.d,
            scale.c,
            scale.h-12,
            null,
            scale.h-12,
            scale.c,
            scale.d,
            null,
            scale.e,
            null,
            scale.c,
            null,
            scale.a-12,
            null,
            scale.a-12,
            null,
            null,
            null,
            null,
            scale.d,
            null,
            scale.f,
            scale.a,
            null,
            scale.g,
            scale.f,
            scale.e,
            null,
            scale.e,
            scale.c,
            scale.e,
            null,
            scale.d,
            scale.c,
            scale.h-12,
            null,
            scale.h-12,
            scale.c,
            scale.d,
            null,
            scale.e,
            null,
            scale.c,
            null,
            scale.a-12,
            null,
            scale.a-12,
            null,
            null,
            null,
            // part 2
            scale.e,
            null,
            scale.c,
            null,
            scale.d,
            null,
            scale.h-12,
            null,
            scale.c,
            null,
            scale.a-12,
            null,
            scale.gis-12,
            null,
            scale.h-12,
            null,
            scale.e,
            null,
            scale.c,
            null,
            scale.d,
            null,
            scale.h-12,
            null,
            scale.c,
            scale.e,
            scale.a,
            null,
            scale.gis,
            null,
            null,
            null
        ]
    }, {
        name: 'alto',
        startAt: (56+96-1),
        endAt: Infinity,
        notes: [
            // part 1
            scale.h-12,
            null,
            scale.gis-12,
            scale.a-12,
            scale.h-12,
            null,
            scale.a-12,
            scale.gis-12,
            scale.e-12,
            null,
            scale.e-12,
            scale.a-12,
            scale.c,
            null,
            scale.h-12,
            scale.a-12,
            scale.gis-12,
            null,
            null,
            null,
            scale.h-12,
            null,
            scale.c-12,
            null,
            scale.a-12,
            null,
            scale.e-12,
            null,
            scale.e-12,
            null,
            null,
            null,
            null,
            scale.f-12,
            null,
            scale.a-12,
            scale.c,
            null,
            scale.h-12,
            scale.a-12,
            scale.g-12,
            null,
            scale.g-12,
            scale.e-12,
            scale.g-12,
            null,
            scale.f-12,
            scale.e-12,
            scale.gis-12,
            null,
            null,
            null,
            scale.h-12,
            null,
            scale.c-12,
            null,
            scale.a-12,
            null,
            scale.e-12,
            null,
            scale.e-12,
            null,
            null,
            null,
            // part 2
            scale.c,
            null,
            scale.a-12,
            null,
            scale.h-12,
            null,
            scale.gis-12,
            null,
            scale.a-12,
            null,
            scale.e-12,
            null,
            scale.e-12,
            null,
            scale.gis-12,
            null,
            scale.c,
            null,
            scale.a-12,
            null,
            scale.h-12,
            null,
            scale.gis-12,
            null,
            scale.a-12,
            scale.c,
            scale.e,
            null,
            scale.e,
            null,
            null,
            null
        ]
    }, {
        name: 'bass',
        startAt: 55, // start at thr 56th note
        endAt: Infinity,
        notes: [
            // part 1
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.gis-(3*12)+12,
            scale.gis-(2*12)+12,
            scale.gis-(3*12)+12,
            scale.gis-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(3*12)+12,
            scale.h-(3*12)+12,
            scale.c-(2*12)+12,
            scale.d-(3*12)+12,
            scale.d-(2*12)+12,
            scale.d-(3*12)+12,
            scale.d-(2*12)+12,
            scale.d-(3*12)+12,
            scale.d-(2*12)+12,
            scale.d-(3*12)+12,
            scale.d-(2*12)+12,
            scale.c-(3*12)+12,
            scale.c-(2*12)+12,
            scale.c-(3*12)+12,
            scale.c-(2*12)+12,
            scale.c-(3*12)+12,
            scale.c-(2*12)+12,
            scale.c-(3*12)+12,
            scale.c-(2*12)+12,
            scale.g-(4*12)+12,
            scale.g-(3*12)+12,
            scale.g-(4*12)+12,
            scale.g-(3*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.e-(3*12)+12,
            scale.e-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            scale.a-(3*12)+12,
            scale.a-(2*12)+12,
            // part 2
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.a-(2*12),
            // scale.e-(1*12),
            scale.gis-(2*12),
            scale.e-(1*12),
            scale.gis-(1*12),
            scale.gis-(2*12)
        ]
    }
]

module.exports = {
    voices,
    label: 'Korobeiniki',
    instrument: 'https://surikov.github.io/webaudiofontdata/sound/0800_SBLive_sf2.js'
}
